/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scheduler.forms;

import java.util.Date;

/**
 *
 * @author James
 */
public class EventPanel extends javax.swing.JPanel {

    /**
     * Creates new form EventPanel
     */
    public EventPanel() {
        initComponents();
    }

    public int[] getDate() {
        int[] mdy = new int[3];
        Date date = dateSelector.getDate();
        mdy[0] = date.getMonth() + 1;
        mdy[1] = date.getDate();
        mdy[2] = date.getYear() + 1900;
        return mdy;
    }

    public String getDescription() {
        if (description.getText() == "") return "";
        if (description.getText() == null) return "";
        return description.getText();
    }

    public String getEventType() {
        return String.valueOf(typeSelector.getSelectedItem());
    }

    public void setDate(Date date) {
        dateSelector.setDate(date);
    }

    public void setDescription(String desc) {
        description.setText(desc);
    }

    public void setSelectedType(String choice) {
        int index = 0;
        switch (choice) {
            case "Homework":
                index = 0;
                break;
            case "Exam":
                index = 1;
                break;
            case "Reminder":
                index = 2;
                break;
            case "Other":
                index = 3;
        }
        typeSelector.setSelectedIndex(index);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        description = new javax.swing.JTextField();
        descLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        typeSelector = new javax.swing.JComboBox<>();
        typeLabel = new javax.swing.JLabel();
        dateSelector = new com.toedter.calendar.JDateChooser();

        description.setToolTipText("");

        descLabel.setText("Description of Event");

        dateLabel.setText("Date");

        typeSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homework", "Exam", "Reminder", "Other" }));

        typeLabel.setText("Type of Event");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typeSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(typeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dateLabel)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(dateSelector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(descLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(description, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeLabel)
                            .addComponent(dateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeSelector))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dateSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private com.toedter.calendar.JDateChooser dateSelector;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextField description;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JComboBox<String> typeSelector;
    // End of variables declaration//GEN-END:variables
}
